---
title: "Figure5"
author: "Raheel R Ahmad"
output: html_notebook
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

# Data Repo
knitr::opts_knit$set(root.dir = normalizePath("/home/jon/Documents/weng_lab/figure_repo")) 

```



```{r Analysis for Figure5A - Building ML Models}
# The method below can be used to build both MEEN and MERF models
# LOAD LIBRARIES:
library(tidyverse)
#library(ranger)
library(gtools)
library(glmnet)
source('../utility_functions/scripts-Project_Independent/regression_functions.R')
source('../utility_functions//mixed_effect_regressionForest.R')
source('../utility_functions//mixed_effect_regressionForest_ranger.R')
source('../utility_functions//mixed_effect_elasticNet_glmnet_parallel.R')
source('../utility_functions//machine_learning_functions.R')
version <- '3.1.0'

# LOAD DATA:
data <- t(as.matrix(readRDS("./batchCorrected_matrix_clusterFltr_logNorm_log2.Rds")))
meta <- tibble(barcode = rownames(data)) %>% 
  inner_join(read_csv("clustering_metadata_logNorm.csv", guess_max = 100000), by = "barcode") %>% 
  inner_join(read_csv("pheno_assgnmnt_logNorm.csv", guess_max = 100000), by = "cluster") %>%
  filter(cell == 'CD8')

# CREATE METADATA VECTORS:
Sex <- c(meta$Sex)
Sex[Sex=='M'] <- 1
Sex[Sex=='F'] <- 0
Sex <- as.numeric(Sex)
data_matrix <- cbind(data[meta$barcode,], Sex) #tail(colnames(data_matrix))
cluster.id <- c(meta$Code) #c(rep(10, nrow(meta[[1]])),meta[[2]]$ID)
cluster.id[str_detect(cluster.id, 'BL')] <- 'cross-sectional'
Y <- meta$Age #c(meta[[1]]$Age,meta[[2]]$Age_r)
Y[Y == 0.1] <- 0
Y[Y == 83.1] <- 83

# MERF METHODS:
df <- data.frame(cluster.id = cluster.id, Y = Y, data_matrix) %>% arrange(cluster.id)
saveRDS(df, './3.5.5_MEEN_glmnet_integrated_DATA_OneGrp_logNorm_parallel.Rds')
# TESTING:
#df <- sample_n(df, 100)
#colnames(df) <- c('cluster.id', 'Y', sprintf("X%s",1:(dim(df)[2]-2)))
xnam = colnames(df)[-c(1,2)]
ni <- (df %>% group_by(cluster.id) %>% summarize(sum = n()))$sum
Yi = split(df$Y, df$cluster.id)
Zi.ri = list(); length(Zi.ri)= length(ni)
q = 1
for(i in 1:length(Zi.ri))   {
  Zi.ri[[i]] <- matrix(rep(1,ni[i]),nrow=ni[i],ncol=q)  
}
Zi = Zi.ri
#Zi = Zi.ric

# BUILD MEEN Model:
old <- Sys.time() # get start time
#MERF.fit <- MERF(#_ranger(
MEEN.fit <- MEEN_glmnet(
  xnam = xnam
  
  ,MERF.lDB = df
  
  ,ni = ni
  ,Zi = Zi
  ,Yi	= Yi
  
  ,model_type = 'enet'
  ,alpha = 0.5 
  ,name_model = '..'
  ,n_fold = 10
  
  
  ,sigmasqzero = NULL
  ,Dzero = NULL
  ,bizero = NULL
  
  ,F.niter = 2 
  ,max.niter = 10
  ,smallest.Jump.allowed = 1e-04
  
  ,verbose = TRUE
  ,ncore = 10
)

new <- Sys.time() - old # calculate difference
print(new)

#str(MERF.fit)

saveRDS(MEEN.fit, './3.5.5_MEEN_glmnet_integrated_OneGrp_logNorm_parallel.Rds')

library(tidyverse)
source('../utility_functions//regression_functions.R')
library(ranger)
library(gtools)
source('../utility_functions//mixed_effect_regressionForest.R')
source('../utility_functions//mixed_effect_regressionForest_ranger.R')
source('../utility_functions//mixed_effect_regressionForest_biglasso.R')
source('../utility_functions//machine_learning_functions.R')
library(ranger)
version <- '3.1.0'

# load integrated data:
data <- t(as.matrix(readRDS("./batchCorrected_matrix_clusterFltr_logNorm_log2.Rds")))
meta <- tibble(barcode = rownames(data)) %>% 
  inner_join(read_csv("./clustering_metadata_logNorm.csv", guess_max = 100000), by = "barcode") %>% 
  inner_join(read_csv("./pheno_assgnmnt_logNorm.csv", guess_max = 100000), by = "cluster") %>%
  filter(cell == 'CD8')

# Create Metadata Vectors:
Sex <- c(meta$Sex)
Sex[Sex=='M'] <- 1
Sex[Sex=='F'] <- 0
Sex <- as.numeric(Sex)
data_matrix <- cbind(data[meta$barcode,], Sex) #tail(colnames(data_matrix))
cluster.id <- c(meta$Code) #c(rep(10, nrow(meta[[1]])),meta[[2]]$ID)
cluster.id[str_detect(cluster.id, 'BL')] <- 'cross-sectional'
Y <- meta$Age #c(meta[[1]]$Age,meta[[2]]$Age_r)
Y[Y == 0.1] <- 0
Y[Y == 83.1] <- 83


# MERF METHODS:
df <- data.frame(cluster.id = cluster.id, Y = Y, data_matrix) %>% arrange(cluster.id)
saveRDS(df, 'MERF_ranger/3.5.5_MERF_ranger_500tree_3000mtry_100ndsize_IntegratedData_30dim1500genes_fixed_DATA_OneGrp_logNorm.Rds')
# TESTING:

xnam = colnames(df)[-c(1,2)]
ni <- (df %>% group_by(cluster.id) %>% summarize(sum = n()))$sum
Yi = split(df$Y, df$cluster.id)
Zi.ri = list(); length(Zi.ri)= length(ni)
q = 1
for(i in 1:length(Zi.ri))   {
  Zi.ri[[i]] <- matrix(rep(1,ni[i]),nrow=ni[i],ncol=q)  
}
Zi = Zi.ri
#Zi = Zi.ric

### MERF application ###
old <- Sys.time() # get start time
#MERF.fit <- MERF(#_ranger(
MERF.fit <- MERF_ranger(
  xnam=xnam
  ,MERF.lDB = df
  ,ni = ni
  ,Zi = Zi
  ,Yi = Yi

  ,ntree= 500
  ,mtry= 3000
  ,nodesize= 100

  ,sigmasqzero = NULL
  ,Dzero = NULL
  ,bizero = NULL

  ,F.niter=2
  ,max.niter= 10
  ,smallest.Jump.allowed = 1e-4

  ,verbose= TRUE
  ,ncore= 120
)

new <- Sys.time() - old # calculate difference
print(new)


saveRDS(MERF.fit, './3.5.5_MERF_ranger_500tree_3000mtry_100ndsize_IntegratedData_30dim1500genes_fixed_OneGrp_logNorm.Rds')

```

```{r Figure5A}
library(tidyverse)
library(gtools)
library(glmnet)

# external scripts (in /scripts folder on GitHub repo)
source('../utility_functions/matrix_functions.R')
source('../utility_functions/regression_functions.R')
source('../utility_functions/mixed_effect_regressionForest.R')
source('../utility_functions/mixed_effect_regressionForest_ranger.R')
source('../utility_functions/mixed_effect_elasticNet_glmnet_parallel.R')
source('../utility_functions/machine_learning_functions.R')
library(ranger)
library(Metrics)
library(ggridges)

version <- '3.6.0'

rf.model <- readRDS('./3.5.5_MERF_ranger_500tree_3000mtry_100ndsize_IntegratedData_30dim1500genes_fixed_OneGrp_logNorm.Rds')
enet.model <- readRDS("./3.5.5_MEEN_glmnet_integrated_OneGrp_logNorm_parallel_geneNameFix.Rds")
df <- readRDS('./3.5.5_MERF_ranger_500tree_3000mtry_100ndsize_IntegratedData_30dim1500genes_fixed_DATA_OneGrp_logNorm.Rds')

# ENET:
fit.enet <- enet.model$fit.enet
currInd <- match(fit.enet$lambda.min,fit.enet$glmnet.fit$lambda)
predictions <- as.numeric(fit.enet$fit.preval[,currInd])
bi <- as.numeric(enet.model$`bi[[r]]`)
bi_data <- tibble(bi = bi, ID = unique(df$cluster.id))


predict_df <- tibble(Age = df$Y, ID = df$cluster.id,  prediction = predictions) %>% inner_join(bi_data, by = 'ID')

predict_df <- predict_df %>% group_by(ID,Age)
predict_df <- predict_df %>% mutate(facet = ifelse(ID == 'cross-sectional', 'cross-sectional', 'longitudinal'))
predict_df$facet <- factor(predict_df$facet, levels = c('longitudinal', 'cross-sectional'))
predict_df$group <- paste(predict_df$Age, predict_df$facet, sep='_')


m.p<-ggplot(predict_df, aes(x=Age, y = prediction + bi)) +
  theme_minimal() + theme_bw(base_size = 7)  + 
  theme(aspect.ratio = 1, legend.position = 'none', axis.title.x = element_blank(), axis.title.y = element_blank()) +
  geom_abline(intercept = 0, slope = 1, color = 'grey40', linetype = 2) +
  geom_boxplot(width = 0.7, aes(group=group, fill = facet), lwd = 0.25, color = 'grey30', outlier.alpha = 0) +
  geom_smooth(data = predict_df[predict_df$facet == 'longitudinal',], method = 'lm', aes(group = ID, color = 'darkred',alpha = 5), size = 0.25, se = F) +
  geom_smooth(method = 'lm', size = 0.65, color = 'darkblue') + 
  coord_cartesian(xlim = c(-10,96), ylim = c(-10,95)) +
  scale_x_continuous(breaks = c(0,20,40,60,80,100)) +
  scale_y_continuous(breaks = c(0,20,40,60,80,100))
print("Figure 4A")
ggsave("fig4a.png")
print(m.p)
write.csv(predict_df, "fig4a_predict_df.csv")

## DENSITY PLOTS
for (group_id in unique(predict_df$group)){
  predict_sub <- filter(predict_df, group==group_id)
  density_plot <- ggplot(predict_sub, aes(x=prediction)) + 
    geom_density() +
    geom_vline(aes(xintercept=unique(Age)), 
               color="blue", linetype='dashed', size=1)
  print(density_plot)
  dir.create('density_plots')
  ggsave(paste0("density_plots/density_", group_id, ".png"))
  #break
}

```


```{r Figure5B_1}
### part 1 predicts on a validation portion of training data source
library(tidyverse)
library(gtools)
library(glmnet)

# external scripts (in /scripts folder on GitHub repo)
source('../utility_functions/matrix_functions.R')
source('../utility_functions/regression_functions.R')
source('../utility_functions/mixed_effect_regressionForest.R')
source('../utility_functions/mixed_effect_regressionForest_ranger.R')
source('../utility_functions/mixed_effect_elasticNet_glmnet_parallel.R')
source('../utility_functions/machine_learning_functions.R')

library(ranger)
library(Metrics)
library(ggridges)

rf.model <- readRDS('./3.5.5_MERF_ranger_500tree_3000mtry_100ndsize_IntegratedData_30dim1500genes_fixed_OneGrp_logNorm.Rds')
enet.model <- readRDS("./3.5.5_MEEN_glmnet_integrated_OneGrp_logNorm_parallel_geneNameFix.Rds")
df <- readRDS('./3.5.5_MERF_ranger_500tree_3000mtry_100ndsize_IntegratedData_30dim1500genes_fixed_DATA_OneGrp_logNorm.Rds')

# for ENET:
fit.enet <- enet.model$fit.enet
currInd <- match(fit.enet$lambda.min,fit.enet$glmnet.fit$lambda)
predictions <- as.numeric(fit.enet$fit.preval[,currInd])
bi <- as.numeric(enet.model$`bi[[r]]`)
bi_data <- tibble(bi = bi, ID = unique(df$cluster.id))

predictions_meta <- read_csv('./3.5.5_MEEN_glmnet_integrated_META_OneGrp_logNorm_parallel.csv', guess_max = 100000)
all.validation <- fit.enet$fit.preval[,67] # get the validation predictions for all cells

validation.df <- data.frame(prediction=all.validation,
  Age=predictions_meta$Age) %>%
  filter(Age>5&(Age<30|Age>70)) %>%
  mutate(Age_Group=ifelse(Age>40,"Old","Young"))
validation.df$Age_Group <- factor(validation.df$Age_Group, levels = c('Young','Old'))

m.p<-ggplot(validation.df, aes(x=Age_Group, y=prediction)) +
  geom_violin(aes(fill = Age_Group)) +
  scale_fill_manual(values = c('pink', 'darkred')) +
  theme_minimal() + theme_bw(base_size = 6) +
  geom_boxplot(width=0.1) +
  coord_cartesian(ylim = c(3,97)) +
  scale_y_continuous(breaks = c(0,20,40,60,80,100))

print("Figure 4B_1")
ggsave("fig_4b_1.png")
write.csv(validation.df, "fig4b_validation_df.csv")
print(m.p)

# MERF Graphs:
predictions <- rf.model$fit.ranger$predictions
bi <- rf.model$`bi[[r]]`
bi_data <- tibble(bi = bi, ID = unique(df$cluster.id))

predict_df <- tibble(Age = df$Y, ID = df$cluster.id,  prediction = predictions) %>% inner_join(bi_data, by = 'ID')

predict_df <- predict_df %>% group_by(ID,Age)
predict_df <- predict_df %>% mutate(facet = ifelse(ID == 'cross-sectional', 'cross-sectional', 'longitudinal'))
predict_df$facet <- factor(predict_df$facet, levels = c('longitudinal', 'cross-sectional'))
predict_df$group <- paste(predict_df$Age, predict_df$facet, sep='_')
# for MERF prediction: y = prediction + bi

predict_df <- predict_df %>% filter(Age > 5 & Age <= 30 | Age >= 70)
predict_df <- predict_df %>% mutate(Age_Group = ifelse(Age > 40, 'Old', 'Young'))
predict_df$Age_Group <- factor(predict_df$Age_Group, levels = c('Young','Old'))
m.p<-ggplot(predict_df, aes(x=Age_Group, y=prediction + bi)) +
  geom_violin(aes(fill = Age_Group)) +
  scale_fill_manual(values = c('pink', 'darkred')) +
  theme_minimal() + theme_bw(base_size = 6) +
  geom_boxplot(width=0.1) +
  coord_cartesian(ylim = c(3,97)) +
  scale_y_continuous(breaks = c(0,20,40,60,80,100))
print("Supplemental Figure4D")
ggsave("supp_fig_4d.png")
write.csv(validation.df, "fig4b_predict_df.csv")
print(m.p)
```


```{r Figure5B_2}
# on external data (Fig4B_2):
# Restart R for package compatibility!!!!! (restarting unloads all packages)

library(tidyverse)
library(Seurat)
library(ranger)
library(psych)
library(tensorflow)
library(keras)
library(glmnet)
require(methods)

suppressMessages({
test_list <- read_csv('./4.4.0_test_list.csv')
})
test_list$sample <- c(1:15)
rf_data <- readRDS('./3.5.5_MERF_ranger_500tree_3000mtry_100ndsize_IntegratedData_30dim1500genes_fixed_DATA_OneGrp_logNorm.Rds')
final <- readRDS('./4.4.0_TestMatrix_geneNameFix.Rds')
labels <- abs(parse_number(rownames(final)))

# RF Model:
RF.model <- readRDS('./3.5.5_MERF_ranger_500tree_3000mtry_100ndsize_IntegratedData_30dim1500genes_fixed_OneGrp_logNorm.Rds')
RF.fit <- RF.model$fit.ranger
# ENET Model:
enet.model <- readRDS("./3.5.5_MEEN_glmnet_integrated_OneGrp_logNorm_parallel_geneNameFix.Rds")
fit.enet <- enet.model$fit.enet

predictions_log2 <- predict(fit.enet, newx = final, s="lambda.min")
pred_tbl <- tibble(sample=labels, prediction=predictions_log2[,1])
pred_tbl <- pred_tbl %>% inner_join(test_list)
pred_tbl$Age_Group <- pred_tbl$Age
pred_tbl$Age_Group <- factor(pred_tbl$Age_Group, levels = c('Young','Old'))
m.p<-ggplot(pred_tbl, aes(x=factor(Age_Group), y=prediction)) +
  geom_violin(aes(fill = Age_Group))+
  scale_fill_manual(values = c('pink', 'darkred')) +
  theme_minimal() + theme_bw(base_size = 6) +
  geom_boxplot(width=0.1) +
  coord_cartesian(ylim = c(3,97)) +
  scale_y_continuous(breaks = c(0,20,40,60,80,100))


print("Figure 4B_2")
ggsave("Figure_4B_2.png")
print(m.p)
write.csv(pred_tbl, "fig4b_2_pred_tbl.csv")

# Supplementary Prediction for RF model:
final_RF <- final
colnames(final_RF) <- str_replace_all(colnames(final_RF), '-', '.')
predictions_log2 <- predict(RF.fit, data = final_RF)
pred_tbl <- tibble(sample=labels, prediction=predictions_log2$predictions)
pred_tbl <- pred_tbl %>% inner_join(test_list)
pred_tbl$Age_Group <- pred_tbl$Age
pred_tbl$Age_Group <- factor(pred_tbl$Age_Group, levels = c('Young','Old'))
m.p<-ggplot(pred_tbl, aes(x=factor(Age_Group), y=prediction)) +
  geom_violin(aes(fill = Age_Group))+
  scale_fill_manual(values = c('pink', 'darkred')) +
  theme_minimal() + theme_bw(base_size = 6) +
  geom_boxplot(width=0.1) +
  coord_cartesian(ylim = c(3,97)) +
  scale_y_continuous(breaks = c(0,20,40,60,80,100))


print("Figure 4B_2_supplemental")
ggsave("Figure_4B_2_supplemental.png")
print(m.p)
write.csv(pred_tbl, "fig4b_2_pred_tbl_supplemental.csv")

pred_tbl_sum <- pred_tbl %>% group_by(Age) %>% summarize(pred = mean(prediction))
ttest <- t.test(pred_tbl[pred_tbl$Age == 'Young',]$prediction, pred_tbl[pred_tbl$Age == 'Old',]$prediction)
ttest$p.value
pred_tbl_sum[pred_tbl_sum$Age == 'Young',]$pred - pred_tbl_sum[pred_tbl_sum$Age == 'Old',]$pred

```



```{r Variable Importance For ML Models}
# VERSION: 4.6.0_6.8.0_MachineLearning_VariableImportance_Bins_MEEN_040822; PREVIOUS: ; STEP: Figure4
# 1) Parse single-cell counts and metadata
# 2) Plot tSNE projection
#SEURAT TUTORIAL: https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html

# LOAD LIBRARIES:
library(tidyverse)
library(DALEX)
library(glmnet)
library(ranger)
source('../utility_functions/machine_learning_functions.R')

# LOAD DATA:
test_data <- readRDS('./3.5.5_MERF_ranger_500tree_3000mtry_100ndsize_IntegratedData_30dim1500genes_fixed_DATA_OneGrp_logNorm_geneNameFix.Rds')
enet.model <- readRDS('./3.5.5_MEEN_glmnet_integrated_OneGrp_logNorm_parallel_geneNameFix.Rds')
fit.enet <- enet.model$fit.enet
currInd <- match(fit.enet$lambda.min,fit.enet$glmnet.fit$lambda)
test_labels <- as.numeric(fit.enet$fit.preval[,currInd])
tp <- test_labels

# ANALYSIS:
# ENET MODEL:
# Generate Model Explainer:
pred <- function(model, newdata)  {
  predictions_log2 <- predict(model, newx = newdata, s="lambda.min")
  return(predictions_log2[,1])
}
newdata <- as.matrix(test_data[,-c(1,2)])
exp_MEEN <- DALEX::explain(model = enet.model$fit.enet, data = newdata, 
                     y = as.numeric(tp),
                     predict_function = pred, label = "MEEN")
vi_keras <- variable_importance(exp_MEEN)
write.csv(vi_keras, './4.6.0_variable_importance_MEEN.csv', row.names=F)

# RF Model:
rf.model <- readRDS('./3.5.5_MERF_ranger_500tree_3000mtry_100ndsize_IntegratedData_30dim1500genes_fixed_OneGrp_logNorm_geneNameFix.Rds')
fit.rf <- rf.model$fit.ranger
currInd <- match(fit.enet$lambda.min,fit.enet$glmnet.fit$lambda)
test_labels <- as.numeric(fit.enet$fit.preval[,currInd])
tp <- test_labels

# Generate Model Explainer:
pred_rf <- function(model, newdata)  {
  predictions_log2 <- predict(model, data = newdata)
  return(predictions_log2$predictions)
}
newdata <- as.matrix(test_data[,-c(1,2)])
exp_MERF <- DALEX::explain(model = rf.model$fit.ranger, data = newdata, 
                           y = as.numeric(tp),
                           predict_function = pred_rf, label = "MERF")
vi_keras <- variable_importance(exp_MERF)
write.csv(vi_keras, './4.6.0_variable_importance_MERF.csv', row.names=F)

# END
```

