---
title: "Figure7"
author: "Humza Hemani"
output: html_notebook
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

# Data Repo
knitr::opts_knit$set(root.dir = normalizePath("/home/jon/Documents/weng_lab/figure_repo")) 

```


```{r Figure7a}
## get HIV age predictions

library(Matrix)

library(tidyverse)
library(Seurat)
library(ranger)
library(psych)
library(tensorflow)
library(keras)
library(glmnet)

require(methods)
# BiocManager::install("org.Hs.eg.db")

add_dummy_genes_to_matrix <- function(data_matrix, gene_list_original) {
  
  # identify missing genes:
  pbmc_genes <- rownames(data_matrix)
  genes_dummy <- gene_list_original[!(gene_list_original %in% pbmc_genes)]
  genes_absent <- pbmc_genes[!(pbmc_genes %in% gene_list_original)]

  print(length(genes_dummy))
  print(length(genes_absent))
  
  # identify all possible names of genes that are 'missing'
  library(org.Hs.eg.db)
  convert <- AnnotationDbi::select(org.Hs.eg.db, keys = genes_absent, columns="SYMBOL",keytype="ALIAS")
  
  # extract the names of the genes that match
  converted_genes <- convert[convert$SYMBOL %in% genes_dummy,]
  colnames(converted_genes)[1] <- 'gene'
  converted_genes <- converted_genes %>% group_by(SYMBOL) %>% sample_n(1)
  converted_genes <- converted_genes[converted_genes$gene %in% pbmc_genes,]
  converted_genes <- converted_genes[converted_genes$SYMBOL %in% gene_list_original,]
  pbmc_df <- tibble(gene=pbmc_genes) %>% left_join(converted_genes, by = 'gene')
  pbmc_df <- pbmc_df %>% group_by(gene) %>% sample_n(1) %>% ungroup()
  pbmc_df2 <- tibble(gene=pbmc_genes) %>% left_join(pbmc_df, by = 'gene')
  pbmc_df <- pbmc_df2 %>% mutate(gene = ifelse(is.na(SYMBOL), gene, SYMBOL))
  
  newrownames <- pbmc_df$gene
  genes_dummy <- gene_list_original[!(gene_list_original %in% newrownames)]
  
  
  empty_mat <- matrix(rep(0, length(genes_dummy) * ncol(data_matrix)), ncol = ncol(data_matrix))
  rownames(empty_mat) <- genes_dummy
  
  
  rownames(data_matrix) <- newrownames
  test_data <- rbind(data_matrix, empty_mat)
  test_data <- test_data[gene_list_original,]
  
  return(test_data)
  
}

seu_obj <- readRDS("./CD8_cells.Rds")
all.dat <- seu_obj[['RNA']]@data
all.dat <- all.dat[(rownames(all.dat) != "Sex"),]
all.dat <- rbind(all.dat, Sex=rep(0,ncol(all.dat))) # 0 for female, 1 for male.

######
enet.model <- readRDS('./3.5.5_MEEN_glmnet_integrated_OneGrp_logNorm_parallel_geneNameFix.Rds')
fit.enet <- enet.model$fit.enet

model.features <- fit.enet[["glmnet.fit"]][["beta"]]@Dimnames[[1]]

print(dim(all.dat))
print(class(all.dat))
all.dat <- t(add_dummy_genes_to_matrix(all.dat, model.features))
saveRDS(all.dat, './test_data_figure4E.Rds')
print(dim(all.dat))
print(class(all.dat))

all.dat.mat <- as.matrix(all.dat)

prediction <- predict(fit.enet, newx = all.dat.mat, s="lambda.min")
saveRDS(prediction, "age_predictions_CD8.Rds")

## load in and plot the predictions
library(tidyverse)
library(Seurat)
library(Matrix)
library(rstatix)
library(ggpubr)

seu_metadata <- readRDS(file = "./CD8_cells_metadata.Rds")
metadata <- as_tibble(read.table(file = './alexandria_structured_metadata.txt', 
                       sep = '\t', header = TRUE))
age_predictions <- readRDS("./age_predictions_CD8.Rds")
clust <- seu_metadata$seurat_clusters

wanted_meta <- dplyr::select(metadata, TimePoint, organism_age, donor_id)
row.names(wanted_meta) <- metadata$NAME
df <- merge(wanted_meta, age_predictions[,1], by=0)
df <- cbind(df, clust)
df <- mutate(df, prediction = y, time_point = TimePoint, actual=organism_age) %>% dplyr::select(-y, -TimePoint, -organism_age)
df <- df %>% mutate(actual = as.numeric(actual))

time_point_ordering <- c("Pre-Infection",
                         "0 Weeks",
                         "1 Week",
                         "2 Weeks",
                         "3 Weeks",
                         "4 Weeks",
                         "6 Months",
                         "1 Year")
replacer <- c("Pre_Infection",
               "0_Weeks",
               "1_Week",
               "2_Weeks",
               "3_Weeks",
               "4_Weeks",
               "6_Months",
               "1_Year")
names(replacer) <- time_point_ordering
df <- df %>% 
  mutate(time_point = factor(time_point, ordered=T,
                                        levels = time_point_ordering),
                    donor_id = factor(donor_id)) %>%
  mutate(time_point = recode(time_point, !!!replacer))%>%
  mutate(time_point = factor(time_point, ordered=F))

age_diff <- c(0, 0, 1/52, 2/52, 3/52, 4/52, 1/2, 1)
names(age_diff) <- c("Pre_Infection",
                     "0_Weeks",
                     "1_Week",
                     "2_Weeks",
                     "3_Weeks",
                     "4_Weeks",
                     "6_Months",
                     "1_Year")


df <- df  %>% mutate(actual = actual+age_diff[time_point])
df <- df  %>% mutate(residual = prediction-actual)

df <- df %>% filter(time_point=="Pre_Infection"|time_point=="1_Year")

## isolate data for Fig4F
cluster <- "0"
this_cluster <- df[df$clust==cluster,] %>% 
  dplyr::select(time_point, residual) %>%
  mutate(time_point = factor(time_point, ordered=F)) %>%
  droplevels()
tp_levels <- levels(this_cluster$time_point)
comps <-list(rep(tp_levels[1], length(tp_levels) -1),
                   tp_levels[2:length(tp_levels)])
print(cluster)
print(comps)
print(dim(this_cluster))
num_at_timepoint <- table(this_cluster$time_point)
for (i in names(num_at_timepoint)){
  #print(num_at_timepoint[i])
  if (num_at_timepoint[i] < 2){
    print(paste(i, "has", num_at_timepoint[i], "cells"))
    print(dim(this_cluster))
    print(levels(this_cluster$time_point))
    print(table(this_cluster$time_point))
    this_cluster <- this_cluster %>% filter(time_point!=i)
    this_cluster$time_point<-droplevels(this_cluster$time_point)
    print(dim(this_cluster))
    print(levels(this_cluster$time_point))
    print(table(this_cluster$time_point))
  }
}

stat.test <- this_cluster %>% 
  t_test(residual ~ time_point,
         ref.group = "Pre_Infection") %>%
  adjust_pvalue(method = "BH") %>%
  add_significance() %>%
  add_xy_position(x = "time_point")
print(stat.test)
  
cluster_violin <- ggplot(data=this_cluster, aes(x=time_point, y=residual)) +
  geom_jitter(position = position_dodge(width = 0.2), color = 'black') +
  geom_violin(aes(fill=time_point)) +
  scale_fill_manual(values = c('lightGreen','forestGreen'))+
  theme_minimal() + theme_bw(base_size=6)  +
  geom_boxplot(width = 0.1) +
  stat_pvalue_manual(stat.test, label = "p.adj", size=3)
print("Figure 4E")
ggsave("4E_HIV_violin.png")
print(cluster_violin)
write.csv(this_cluster, "4E_HIV_violin_this_cluster.csv")
```

```{r Figure7b}
## code from 2.1 age_prediction, written by Humza Hemani.
library(tidyverse)
library(glmnet)
library(Seurat)
library(Matrix)

add_dummy_genes_to_matrix <- function(data_matrix, gene_list_original) {
  
  # identify missing genes:
  pbmc_genes <- rownames(data_matrix)
  genes_dummy <- gene_list_original[!(gene_list_original %in% pbmc_genes)]
  genes_absent <- pbmc_genes[!(pbmc_genes %in% gene_list_original)]

  print(paste("genes_dummy", length(genes_dummy)))
  print(paste("genes_absent",length(genes_absent)))
  
  # identify all possible names of genes that are 'missing'
  library(org.Hs.eg.db)
  convert <- AnnotationDbi::select(org.Hs.eg.db, keys = genes_absent, columns="SYMBOL",keytype="ALIAS")
  
  # extract the names of the genes that match
  converted_genes <- convert[convert$SYMBOL %in% genes_dummy,]
  colnames(converted_genes)[1] <- 'gene'
  converted_genes <- converted_genes %>% group_by(SYMBOL) %>% sample_n(1)
  converted_genes <- converted_genes[converted_genes$gene %in% pbmc_genes,]
  converted_genes <- converted_genes[converted_genes$SYMBOL %in% gene_list_original,]
  pbmc_df <- tibble(gene=pbmc_genes) %>% left_join(converted_genes, by = 'gene')
  pbmc_df <- pbmc_df %>% group_by(gene) %>% sample_n(1) %>% ungroup()
  pbmc_df2 <- tibble(gene=pbmc_genes) %>% left_join(pbmc_df, by = 'gene')
  pbmc_df <- pbmc_df2 %>% mutate(gene = ifelse(is.na(SYMBOL), gene, SYMBOL))
  
  newrownames <- pbmc_df$gene
  genes_dummy <- gene_list_original[!(gene_list_original %in% newrownames)]
  
  
  empty_mat <- matrix(rep(0, length(genes_dummy) * ncol(data_matrix)), ncol = ncol(data_matrix))
  rownames(empty_mat) <- genes_dummy
  
  
  rownames(data_matrix) <- newrownames
  test_data <- rbind(data_matrix, empty_mat)
  test_data <- test_data[gene_list_original,]
  
  return(test_data)
  
}

seu_obj <- readRDS("./1.3_only_CD8_reclustered.Rds")

all.dat <- seu_obj[['RNA']]@data
all.dat <- all.dat[(rownames(all.dat) != "Sex"),]
new_sex_row <- plyr::mapvalues(x = seu_obj$Sex,
                               from = c('M','F'),
                               to = c(1,0))# 0 for female, 1 for male.
new_sex_row <- as.numeric(levels(new_sex_row))[new_sex_row]
all.dat <- rbind(all.dat, Sex=new_sex_row) 

######
enet.model <- readRDS('./3.5.5_MEEN_glmnet_integrated_OneGrp_logNorm_parallel_geneNameFix.Rds')
fit.enet <- enet.model$fit.enet

model.features <- fit.enet[["glmnet.fit"]][["beta"]]@Dimnames[[1]]
all.dat <- add_dummy_genes_to_matrix(all.dat, model.features)

print("starting actual prediciton")
prediction <- predict(fit.enet, newx = t(all.dat), s="lambda.min")
saveRDS(prediction, file.path("age_predictions_car_t.Rds"))

## code from 2.2
library(rstatix)
library(ggpubr)

seu_metadata <- readRDS("./1.3_metadata.Rds")
age_prediction <- data.frame(prediction=readRDS("./age_predictions_car_t.Rds")) %>%
  mutate(prediction=`lambda.min`)

# combine the relevate seurat metadata and the age predictions
df <- seu_metadata %>%
  dplyr::select(seurat_clusters,
         Patient, 
         Group, # Group variable refers to the text-based time point e.g. "IP", "Late"
         Disease,
         TimePoint, # TimePoint variable refers to the exact day
         Sex) %>%
        cbind(age_prediction)
df <- df %>% mutate(day = plyr::mapvalues(df$TimePoint,
                                          from = c("d102","d112","d12","d21","d28","d29","d38","d83","d89","IP"),
                                          to = c(102, 112, 12,21,28,29,38,83,89,0))) %>%
  mutate(actual =
               plyr::mapvalues(
                 x = df$Patient,
                 from = c('NHL-9','NHL-10','CLL-1','CLL-2'),
                 to = c(64, 51, 61, 53)
               ) # actual age of each patient
  )
# adjust the actual age of the patients to account for time since diagnosis
df <- df %>% mutate(actual = as.numeric(levels(actual))[actual] + as.numeric(levels(day))[day]/365)

# calculate the difference between the predicted age and actual age
df <- df %>% mutate(residual = prediction - actual)

# Remove Contraction timepoint
# Only looking at IP, Expansion Peak, and Late.
df2 <- df %>% 
  filter(Group!="Contraction") %>%
  mutate(day=droplevels(day), Group=droplevels(Group))

# use the average residual of each person's cells at day 0 as a reference
# subtract that reference from each cell's residual in the dataset
# so we can clearly see how the CAR T-cells age after infusion
ref_map <- numeric(4)
names(ref_map) <- unique(df2$Patient)
for(patient in unique(df2$Patient)){
  wanted_values <- df2$residual[df2$Patient==patient & df2$Group=="IP"]
  print(patient)
  print(mean(wanted_values))
  ref_map[patient] <- mean(wanted_values)
  summary(wanted_values)
  summary(wanted_values-mean(wanted_values))
}
df2 <- df2%>%
  mutate(ref_age=plyr::mapvalues(Patient,
                                 from=names(ref_map),
                                 to=ref_map)) %>%
  mutate(ref_age = as.numeric(levels(ref_age))[ref_age]) %>%
  mutate(adjusted_residual=residual-ref_age)

# get the mean adjusted residual for each patient at each time point
df3 <- df2 %>% group_by(Patient,Group) %>% 
  dplyr::select(actual, prediction, residual, ref_age, adjusted_residual) %>%
  summarise_all(mean) %>% 
  ungroup() %>%
  mutate(Group=factor(Group, levels=c("IP", "ExpansionPeak", "Late")))

# get p values
stat.test <- df3 %>% 
  t_test(residual ~ Group) %>%
  adjust_pvalue(method = "BH") %>%
  add_significance() %>%
  add_xy_position(x = "Group", y.trans=function(x){x+18})
print(stat.test)
# write.csv(stat.test, "overall_stat_test.csv")

# the rest of the script does plotting.
overall_combined <- ggplot(df3, 
                                  aes(x=Group, 
                                      y=adjusted_residual, 
                                      group=Group)) +
  geom_jitter(aes(alpha = 1.0),  position = position_dodge(width = 0.2), color = 'black') +
  #geom_violin(data = filter(df3, Group == "ExpansionPeak" | Group == "Late"),
              #aes(fill=Group)) +
  theme_minimal() + theme_bw() +
  geom_boxplot(data = filter(df3, Group == "ExpansionPeak" | Group == "Late"),
               width = 0.1) +
  stat_pvalue_manual(data=stat.test, label="p.adj", inherit.aes=F, size=3)

overall_with_mean_line <- overall_combined +
  stat_summary(aes(group=1),color='black',fun=mean, geom="line")
print("Figure 4G")
ggsave("fig_4g.png")
print(overall_with_mean_line)
write.csv(df3, "fig4g_df3.csv")
```
